version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ACCOUNT_ID: "784012530518"
    ECR_REPO: cicdpipeline
    IMAGE_TAG: "cicdpipeline-service"   # hardcoded tag

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Using Java and Docker from the standard image"
      - mvn -version
      - docker --version

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - REPO_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO
      - echo "REPO_URI=$REPO_URI  IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - echo "Building Maven artifact..."
      - mvn -q -DskipTests package
      - echo "Building Docker image..."
      - docker build -t $REPO_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPO_URI:$IMAGE_TAG
      - echo "Writing imagedefinitions.json for CodePipeline/CodeDeploy..."
      - printf '[{"name":"cicdpipelinecontainer","imageUri":"%s"}]' "$REPO_URI:$IMAGE_TAG" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
